route:
  receiver: 'mailhog-email'
  group_wait: 5s
  group_interval: 5s
  repeat_interval: 1h

receivers:
  - name: 'mailhog-email'
    email_configs:
      - to: 'admin@stresser.com'
        from: 'alertmanager@stresser.com'
        smarthost: 'mailhog:1025'
        require_tls: false
        send_resolved: true