services:
  stresser-app:
    build: ./stresser-app
    container_name: stresser-app
    ports:
      - "${STRESSER_PORT}:8080"
    environment:
      - STRESSER_PORT=8080
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "512M"