services:
  stresser-app:
    build: ./stresser-app
    container_name: stresser-app
    ports:
      - "${STRESSER_PORT}:8080"
    environment:
      - STRESSER_PORT=8080
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "512M"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    depends_on:
      - stresser-app
